### ISSUE TITLE
Impossible to activate headed mode 

### ISSUE THREAD

**Issue by nboisteault** [cypress-io/github-action#403] opened 2021-07-22 14:18 UTC
Hi,
It seems impossible to activate headed mode with Cypress (8.0) and its Github action.
Look at https://github.com/nboisteault/lizmap-web-client/runs/3134874027?check_suite_focus=true#step:9:5 , I did put : 
```
headless: false
headed: true
```
But action is ran headless : https://github.com/nboisteault/lizmap-web-client/runs/3134874027?check_suite_focus=true#step:9:51

Thanks for you help.

**Comment by Sergiu-B** [comment] 2021-08-03 14:38
Seeing the same issue. It's especially annoying when running visual regression tests, because `headed` vs `headless` renderings of the same page/ component are different. Same goes for using the `clipboard` which is unavailable in `headless` Chrome.

From what I see in the code it doesn't even look for the `headed` prop: 
`const headless = getInputBool('headless')`

**Comment by juandavidkincaid** [comment] 2021-10-07 13:40
+1

**Comment by andrewalc** [comment] 2021-11-30 14:06
realized this today after trying headless: false and seeing it still run in headless mode. seems misleading to me if the headless option is always the default anyway, would really appreciate a headed option

**Comment by HansKre** [comment] 2021-12-04 19:38
Thank you, @andrewalc!
A little hint for anyone coming here in the future, you still need to specify the `build` and `start` commands:

```
uses: cypress-io/github-action@v2
  with:
    build: npm run build
    start: npm start
    command: yarn cypress run --headed --browser chrome
```

**Comment by MikeMcC399** [comment] 2023-07-11 15:40
@ricardo-dematos 

I don't see any remaining problem with `github-action@v5` using the option `headed: true` or `headed: false`.

Could you please explain what you think should be different?

In your example you specified `headed: false` and Cypress ran `headless`, which is correct.

**Comment by nagash77** [comment] 2023-07-12 18:43
Closing as resolved

**Closed by nagash77** 2023-07-12 18:43 UTC
