### ISSUE TITLE
Cancel test run on Cypress cloud when action is cancelled

### ISSUE THREAD

**Issue by cjquines** [cypress-io/github-action#1182] opened 2024-05-21 20:32 UTC
When running the action with `record: true`, if it gets cancelled, the corresponding Cypress cloud run still shows as running, rather than cancelled.

It'd be nice if it got cancelled as well, so the runs that are running on Cypress cloud correspond to Github actions that are also running.

**Comment by jennifer-shehane** [comment] 2024-05-21 20:45
Duplicate of https://github.com/cypress-io/cypress/issues/21125

**Closed by jennifer-shehane** 2024-05-21 20:45 UTC
