### ISSUE TITLE
`cypress-io/github-action` does not distinguish `steps.<step_id>.conclusion` from `steps.<step_id>.outcome`

### ISSUE THREAD

**Issue by ricardo-dematos** [cypress-io/github-action#964] opened 2023-07-14 22:41 UTC
Given the following configuration, when one of the tests fails both `steps.cypress.conclusion` and `steps.cypress.outcome` report `failure` , thus contradicting the [documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context).

```yaml
      - name: 'Run end-to-end tests'
        id: cypress
        timeout-minutes: 15  # must be adjusted with e2e tests progress
        uses: cypress-io/github-action@v5  # see https://github.com/cypress-io/github-action/issues/620
        env:
          ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'  # see https://github.com/cypress-io/cypress/issues/25357
        with:
          working-directory: 'e2e-tests'
          cache-key: "node-cache-${{ runner.os }}-npm-${{ hashFiles('e2e-tests/package-lock.json') }}"  # see https://github.com/cypress-io/github-action/pull/24
          command: 'npx cypress run --e2e --browser ${{ inputs.browser }} --headless --config video=false --env host="${{ inputs.deployment_url }}",username="${{ inputs.deployment_username }}",password="${{ inputs.deployment_password }}"'  # see https://github.com/cypress-io/github-action/issues/489

      - name: 'Print previous step outcome/conclusion'
        id: print
        run: |
          echo "outcome: ${{ steps.cypress.outcome }}"
          echo "conclusion: ${{ steps.cypress.conclusion }}"
        shell: bash
```

As long `cypress-io/github-action` completes with success, it should report `steps.cypress.conclusion=success` .

This may be related to the use of a [custom command](https://github.com/cypress-io/github-action/pull/884).

**Comment by MikeMcC399** [comment] 2023-07-15 11:00
@ricardo-dematos

> Given the following configuration, when one of the tests fails both `steps.cypress.conclusion` and `steps.cypress.outcome` report `failure` , thus contradicting the [documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context).

If you think there is a bug in `github-action` in this respect, please provide a simple reproducible example. However please note my comments:

I cannot see any use of `continue-on-error` in your example. That would be the only reason that `conclusion` and `outcome` would differ. It is probably not a good idea anyway to use `continue-on-error` because that could make the Cypress test look like it passed even it if failed.

The example workflow you posted will not display the step outcomes after an error in the previous step in the job occurs. You could add
`if: always()`
to correct that.

```yaml
      - name: 'Print previous step outcome/conclusion'
        if: always()
```

**Comment by MikeMcC399** [comment] 2023-07-17 07:13
@ricardo-dematos 

I observed the following when I tried this out (without using `continue-on-error`):

| github-action test | `steps.cypress.conclusion` | `steps.cypress.outcome` |
| ------------------ | -------------------------- | ----------------------- |
| pass               | `success`                  | `success`               |
| fail               | `failure`                  | `failure`               |

This agrees with the ['steps' context](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context) documentation, which describes how GitHub's [actions/runner](https://github.com/actions/runner) sets the values `conclusion` and `outcome`.

Your original post said "As long (as) cypress-io/github-action completes with success, it should report steps.cypress.conclusion=success." and this is exactly what I see.

In the screenshots you posted, the job `e2e` test was failing and there was no screenshot showing the value of `steps.cypress.conclusion` / `steps.cypress.outcome`. I would expect both of them to be set to `failure` in this case. I don't see an example of the action succeeding and `conclusion` being wrongly set to `failure`. 

> It should also be noted that the use of a custom command produces an error message:

A `custom` option can produce a failure. It can also be successful. We use it successfully with the[ Yarn Modern Plug'n'Play example](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-yarn-modern-pnp.yml) `command: yarn cypress run`.

Again, if you think there is a bug, then a **simple** reproducible example together with logs would be extremely helpful.

**Comment by MikeMcC399** [comment] 2023-07-17 12:16
@ricardo-dematos 

I tested using the regular way of using `github-action` without using the `command` option. I will retest using the `command` option like you are doing.

> Shouldn't the action produce the step summary, even when the tests fail?

Using `command` disables many features of `github-action` including the test summary (see https://github.com/cypress-io/github-action#custom-test-command which refers to the `publish-summary`), so no, it is not expected for a test summary to be produced.

**Comment by MikeMcC399** [comment] 2023-07-17 12:31
@ricardo-dematos 

I'm sorry, but even after testing using the `command` option I still could not see a problem. I will have to pass this on to the Cypress experts now, as I have run out of ideas about how to help you.

**Comment by MikeMcC399** [comment] 2023-07-18 12:41
@ricardo-dematos 

- Your comments address a much bigger issue than the step results. I have added a new enhancement request https://github.com/cypress-io/github-action/issues/968 to cover some of this. I also mentioned about the disadvantages of the `command` option. I don't think there is any question of the `command` option being removed, since it is in use. Removing it would be a breaking change and would put those who use it at an unnecessary disadvantage. This of course does not mean that you need to continue using it.

**Comment by hckhanh** [comment] 2023-07-23 17:01
> > > Shouldn't the action produce the step summary, even when the tests fail?
> > 
> > 
> > Using `command` disables many features of `github-action` including the test summary (see https://github.com/cypress-io/github-action#custom-test-command which refers to the `publish-summary`), so no, it is not expected for a test summary to be produced.
> 
> I'm trying to use the `cypress-io/github-action` because I want the step summary and the annotations.
> 
> Using the `command` setting seems more and more, to me, the same has using the command line directly (`run: `). 😔
> 
> I don't have the full picture and probably someone has a case for using the `command` setting, but I get the feeling that `command` and `command-prefix` should be removed from the `cypress-io/github-action` and users advised to use the command line directly, if they need something more specific. 🤔

Is there anything else can work with Percy if `command-prefix` is removed?

**Comment by MikeMcC399** [comment] 2023-08-22 07:44
@hckhanh 

> Is there anything else can work with Percy if command-prefix is removed?

`command-prefix` continues to be available as a parameter.

**Comment by MikeMcC399** [comment] 2023-08-28 15:56
@ricardo-dematos 

The release of  `cypress-io/github-action@v6` with full support of Node.js `20` should allow you to now avoid the use of the `command` parameter. You stated elsewhere that [badeball/cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) needs Node.js `18`. (Note that I haven't tested if this works or not.)

**Comment by MikeMcC399** [comment] 2023-09-13 09:10
@ricardo-dematos 

> Given the following configuration, when one of the tests fails both `steps.cypress.conclusion` and `steps.cypress.outcome` report `failure` , thus contradicting the [documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context).

Your original problem description talks about status results which are set by the GitHub https://github.com/actions/runner software and documented in [GitHub Actions > Learn GitHub Actions > Contexts > `steps`context](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context) which you quoted.

This may no longer be a problem for you, however if it is still an issue, then it is not something which `cypress-io/github-action` can resolve, so I suggest to close this issue now.

## Resources

Here are other resource locations which might be helpful to you in case you need further assistance:

- Issue list https://github.com/actions/runner/issues
- [GitHub community forrm: Actions section](https://github.com/orgs/community/discussions/categories/actions)
- [Cypress technical community on Discord](https://on.cypress.io/discord)

**Comment by MikeMcC399** [comment] 2023-11-04 06:59
Closing, as previously suggested.

**Closed by MikeMcC399** 2023-11-04 06:59 UTC
