### ISSUE TITLE
Does not run reliably on a GitHub Ubuntu Runner

### ISSUE THREAD

**Issue by kpturner** [cypress-io/github-action#449] opened 2021-11-03 17:57 UTC
If I run tests using this github action on the Ubuntu@latest runner provided by Github virtually all the tests crash:
```
<--- JS stacktrace --->



We detected that the Chromium Renderer process just crashed.



This is the equivalent to seeing the 'sad face' when Chrome dies.



This can happen for a number of different reasons:



- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium



You can learn more including how to fix Docker here:



https://on.cypress.io/renderer-process-crashed
```

If I try to use Chrome or Firefox instead of Electron the tests just appear to hang.  Actually they do eventually complete but with loads of failures/browser crashes after about 9 hours.

Even if I run cypress without this specific action (but just running `npx cypress --headless`) I get pretty much the same catastrophic failures.

For us it seems cypress seems almost unusable within a github actions runner.

The tests all run smoothly and pass when run externally to github actions.

**Comment by kpturner** [comment] 2021-11-11 15:00
Also, running with Firefox can never produce a video.  You always get an error saying that the video creation failed.

**Comment by kpturner** [comment] 2021-12-15 12:20
It seems I can only get this to work with Firefox 93 and below.

**Comment by MikeMcC399** [comment] 2023-01-23 08:59
@kpturner 

This is an old issue, and I assume that it is mostly already solved, since the workflow examples in https://github.com/cypress-io/github-action/tree/master/.github/workflows are now all working reliably.

> Also, running with Firefox can never produce a video. You always get an error saying that the video creation failed.

- This however is still an open issue https://github.com/cypress-io/cypress/issues/18415

**Comment by MikeMcC399** [comment] 2023-07-11 17:18
Since there is no specific reproducible example linked to this issue, we can't check whether it is still happening or not. Only the original poster @kpturner could say. 

It would only be valuable to keep the issue open if there is a repo supplied which fails with current versions, so I would tend to suggest to close this issue.

Unfortunately it is one of many older issues which have become stale. There is an on-going process on the main [cypress-io/cypress](https://github.com/cypress-io/cypress) repo to clean out stale issues (where there are currently1.3k open issues), however this has not (yet) been applied to this repository (which "only" has about 100 open issues).

**Comment by nagash77** [comment] 2023-07-12 18:28
I am going to close this issue as it is quite old at this point.  If folks are seeing this behavior in current versions of the github-action please open a new ticket with a reproducible example and we will be happy to investigate.

**Closed by nagash77** 2023-07-12 18:28 UTC
