### ISSUE TITLE
Geolocation error on final command of final test

### ISSUE THREAD

**Issue by Fy50167** [cypress-io/github-action#1195] opened 2024-06-05 00:43 UTC
My applications has a dialog that opens up and covers all other elements if locations permissions are not enabled in the browser. Generally this doesn't interfere with my cypress tests whatsoever since we run our tests through Chrome instead of Electron, however in Github Actions (and only in actions, this doesn't occur in cypress locally) on the final action of the final test that gets ran (which is a click), the test fails because the dialog opens up and covers everything. I have no clue what could be causing this to occur since if locations weren't enabled I'm assuming the error would be occurring earlier or in any of the 5 tests that pass before, but for some reason it only shows up on the very last command that gets run.

**Comment by MikeMcC399** [comment] 2024-06-05 05:47
@Fy50167 

The Cypress GitHub Action has no influence on individual steps in a set of tests, so it is very unlikely that there is a bug in the action which would cause the problem you are describing.

You may be able to get help from the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

You can find community members there with a broad base of experience which you can draw on.

**Comment by jennifer-shehane** [comment] 2024-06-05 15:03
@Fy50167 Looks like this may be this issue: https://github.com/cypress-io/cypress/issues/2671 There's a workaround in there.

**Comment by MikeMcC399** [comment] 2024-06-06 05:54
@Fy50167 

- Please let us know if the link to https://github.com/cypress-io/cypress/issues/2671 was helpful to you

**Comment by Fy50167** [comment] 2024-06-07 05:24
> @Fy50167
> 
> * Please let us know if the link to [Automatically accept geolocation permission / mock geolocation for tests cypress#2671](https://github.com/cypress-io/cypress/issues/2671) was helpful to you

Unfortunately not, basically every solution listed is outdated and deprecated at this point.

**Comment by MikeMcC399** [comment] 2024-06-07 05:39
@Fy50167
> Unfortunately not, basically every solution listed is outdated and deprecated at this point.

Do you have a reproduction of this issue which you could share? I would suggest opening a new issue on https://github.com/cypress-io/cypress and using the template there to capture additional details, like version information.

**Comment by MikeMcC399** [comment] 2024-06-07 06:26
Also in Discord
https://discord.com/channels/755913899261296641/1248507254706278441

**Comment by MikeMcC399** [comment] 2024-06-10 06:16
I suggest to close this issue since it cannot be solved by the Cypress GitHub Action.

**Closed** 2024-06-10 15:15 UTC
Labels: unexpected behavior
