### ISSUE TITLE
Problems that always pass visual regression tests run with the GitHub action

### ISSUE THREAD

**Issue by student513** [cypress-io/github-action#639] opened 2022-11-24 07:33 UTC
Any test that intentionally fails in a local environment is always passed when it is run as a GitHub action. I checked the screenshot of the cypress dashboard to see what happens when I run the GitHub action.

The first image is a baseline screenshot.
![image](https://user-images.githubusercontent.com/50268619/203719380-24e9e1dc-57fd-410a-acec-f7cfdc46c725.png)

The second image is a snapshot of the ui intended to fail. An extra button has been added.
![image](https://user-images.githubusercontent.com/50268619/203719486-1a123af0-2f22-4eed-bb85-24fe885dbdc3.png)

As I assume, the test should not pass if the snapshot taken in the second GitHub action test differs from the baseline in the first GitHub action test after the baseline is generated by the first GitHub action test.

In fact, local tests do not pass the above tests. The settings are as follows.
```
// commands.js
import { addMatchImageSnapshotCommand } from "cypress-image-snapshot/command";

addMatchImageSnapshotCommand({
  failureThreshold: 0.001,
  failureThresholdType: "percent",
  customDiffConfig: { threshold: 0.1 },
  capture: "viewport",
});
```
<img width="431" alt="스크린샷 2022-11-24 오후 4 28 24" src="https://user-images.githubusercontent.com/50268619/203720041-ca2d5c78-5cdf-4959-ba87-bc214440aa70.png">

However, if you try to test with GitHub action, all of them succeed.
```
(Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        11.1.0                                                                         │
  │ Browser:        Chrome 107 (headless)                                                          │
  │ Node Version:   v16.13.0 (/home/runner/runners/2.299.1/externals/node16/bin/node)              │
  │ Specs:          1 found (cameraTranslateInDirection.cy.ts)                                     │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  │ Params:         Tag: false, Group: false, Parallel: false                                      │
  │ Run URL:        https://cloud.cypress.io/projects/9iq3e5/runs/3                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  cameraTranslateInDirection.cy.ts                                                (1 of 1)
  Estimated: 9 seconds


  translateInDirection
    ✓ translate to N (2162ms)
    ✓ translate to NE (687ms)
    ✓ translate to E (655ms)
    ✓ translate to SE (621ms)
    ✓ translate to S (636ms)
    ✓ translate to SW (641ms)
    ✓ translate to W (706ms)
    ✓ translate to NW (725ms)
    ✓ translate to backward (976ms)
    ✓ translate to forward (1121ms)


  10 passing (9s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        10                                                                               │
  │ Passing:      10                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  10                                                                               │
  │ Video:        true                                                                             │
  │ Duration:     8 seconds                                                                        │
  │ Estimated:    9 seconds                                                                        │
  │ Spec Ran:     cameraTranslateInDirection.cy.ts                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

The reasons I expect are as follows

- The threshold setting for the github action exists independently, and the default threshold value is more generous than the threshold value I set in the project(cypress.config).
- The test always passes because the baseline of the test to be attempted with the github action is initialized every time. ⇒ If so, how do you generate baseline and where is it stored?

I hope the results of the local test and the test run by GitHub action are the same. I'd really appreciate your help

```
name: CI
on: [push]

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

```
// cypress.config.js
import { defineConfig } from "cypress";
import { addMatchImageSnapshotPlugin } from "cypress-image-snapshot/plugin";

export default defineConfig({
  projectId: '******',
  e2e: {
    setupNodeEvents(on, config) {
      addMatchImageSnapshotPlugin(on, config);
    },
  },
});
```

**Comment by MikeMcC399** [comment] 2023-11-06 14:30
@student513 

Are you still having a problem with the issue you reported?

It does not look like it is something that `github-action` can resolve for you. The action does not have any functionality for visual regression tests, it can only support them in a generic way.

**Comment by MikeMcC399** [comment] 2023-11-09 11:12
Closing, since this issue is out-of-scope.

**Closed by MikeMcC399** 2023-11-09 11:12 UTC

**Comment by maximegheraille** [comment] 2023-12-16 20:10
Hi,

I think I might be having the same issue, where all snapshots checks within the Github action passes and never fails.
The cypress-image-snapshot/plugin plugin compares snapshot's if some exists otherwise it makes new one's.

The main issue from what I can see if that when the actions runs it does never contains those snapshots, even thought they are in the repo and do work locally.

**Comment by MikeMcC399** [comment] 2023-12-17 07:29
@maximegheraille 

- The original issue here was also cross-posted to https://github.com/jaredpalmer/cypress-image-snapshot/issues/261where it has remained open and unanswered. It seems that this plugin is no longer maintained.

Please give some information about your configuration:
- Cypress version
- Local Node.js version
- `cypress-io/github-action` version
- source of `cypress-image-snapshot` you are using and what the version is

There is a replacement package [@simonsmith/cypress-image-snapshot](https://www.npmjs.com/package/@simonsmith/cypress-image-snapshot) published, however I can't give you any recommendation whether this package is good to use. You will need to check this yourself.

**Comment by ghilaslinz** [comment] 2024-07-09 08:24
Anyone solved this problem?  I have exactly the same issue

**Comment by MikeMcC399** [comment] 2024-07-09 08:54
@ghilaslinz 

You may have more luck if you post your question (and / or search for similar topics) from the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)
