### ISSUE TITLE
Cache stores the app BEFORE "build" step

### ISSUE THREAD

**Issue by mleszcz** [cypress-io/github-action#371] opened 2021-05-10 11:31 UTC
That causes we are unable to cache anything we generate in the build action, eg assets.

Expected behaviour: on the initial build, cache the app AFTER build step.

BTW: everything else seem to work very nice and smoothly :+1:

**Comment by bahmutov** [comment] 2021-05-10 13:15
We have never intended for the cache to store additional artifacts like the built site. Think about the folders the action caches - it is just NPM modules and the Cypress binary, not additional user-defined folders.

In fact, I would say caching the built folder is probably an anti-pattern. You want your CI to build the site again, right?

**Comment by mleszcz** [comment] 2021-05-11 06:34
We got a rails app. We'd like to cache our assets (bundle exec rake assets:precompile).
Unfortunatelly turned out that even if we run above rake task and run actions/cache before cypress-io/github-action it's been then overwriten by cypress-io action's cache restore.

I suspect cypress-io action's cache store (when the first GHA build occurs) step stores just some specific folders, and misses our public/assest public/packs-test folders here:
```
25l[12:27:27]  Verifying Cypress can run /home/runner/.cache/Cypress/7.2.0/Cypress [started]
[12:27:29]  Verifying Cypress can run /home/runner/.cache/Cypress/7.2.0/Cypress [completed]
25h25h::debug::saving NPM modules
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/splash-brands/splash-brands --files-from manifest.txt
Cache Size: ~98 MB (102531192 B)
Cache saved successfully
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/splash-brands/splash-brands --files-from manifest.txt
Cache Size: ~187 MB (196234792 B)
Cache saved successfully
```

Then it's always been restored without it, and infact even if restored before by action/cache it got overwritten by cypress-io cache restore.

Maybe you could take a look and would have some suggestion how can we cache our assets.

```
      - name: Extract branch name (used by assets-cache)
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Cache assets
        id: assets-cache
        uses: actions/cache@v2
        with:
          path: |
            public/assets
            public/packs
            public/packs-test
          key: ${{ runner.os }}-assets-${{ steps.extract_branch.outputs.branch }}
      - name: Precompile assets if not cached
        if: steps.assets-cache.outputs.cache-hit != 'true'
        run: bundle exec rake assets:precompile
      - uses: cypress-io/github-action@v2
        with:
          start: bundle exec rails server -e test -p 5017
          wait-on: "http://localhost:5017"
```

We added
```
      - uses: cypress-io/github-action@v2
        with:
          build: bundle exec rake assets:precompile
          start: bundle exec rails server -e test -p 5017
```

this should detect assets (if restored properly) and quickly skip the step, but unfortunatelly it compiles it once again which takes additional 2 minutes.

**Comment by bahmutov** [comment] 2021-05-11 13:49
Hmm, I don't see why Cypress cache would overwrite the `public` folders cache you are using. Can you create a short, small example showing the caching problem in action? I think that you probably want to install everything in one action, run your caching and build logic and then run tests. Separating the install and test steps into two calls to cypress GH action is possible as shown here https://github.com/cypress-io/github-action#split-install-and-tests

**Comment by mleszcz** [comment] 2021-05-18 08:27
You're right it shouldn't affect `public` folder. Seems like there's something wrong with yarn cache in our case. Take a look:
1). seems like everything is ok after the 1st build (yarn packages cached, assets cached) :+1: 
2). but... at the 2nd build after yarn cache is restored it "builds" something again (this is problably why our assets got recompiled)
```
[4/4] Building fresh packages...
Done in 13.75s.
```
3). then when yarn install got executed for the second time (by our assets:precompile's init step)
```
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.63s.
```
it looks like it should actually in (2)

The consequence step (2) does something, our assets:precompile reads as "packages got changed" and despite it was restored from the cache it triggers the recompilation task.

cypress.yml https://gist.github.com/mleszcz/16d80ec77e675d0b302861843576ff6e
1st build
![SB-383 cypress-1](https://user-images.githubusercontent.com/72438/118618082-8bfc3700-b7c3-11eb-8835-181793ff8b5b.png)

2nd build
![SB-383 cypress-2](https://user-images.githubusercontent.com/72438/118618110-91f21800-b7c3-11eb-8e0f-9e7140b7ae76.png)

Thanks A LOT for helping us.

**Comment by mleszcz** [comment] 2021-05-20 12:33
Resolved with https://docs.cypress.io/guides/continuous-integration/github-actions#Caching-Dependencies-and-Build-Artifacts
```
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
            public
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - uses: cypress-io/github-action@v2
        with:
          install: false
          build: bundle exec rake assets:precompile
```

**Comment by MikeMcC399** [comment] 2023-11-04 10:33
Closing, based on previous comment that the issue is resolved.

**Closed by MikeMcC399** 2023-11-04 10:33 UTC
