### ISSUE TITLE
Warning in workflow about set-output

### ISSUE THREAD

**Issue by nehal0412** [cypress-io/github-action#616] opened 2022-10-18 07:54 UTC
**Description:**

Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/104140903/196369105-8ecabc06-fa56-4edf-976f-2aa9f755bd8e.png">

**Version:**
V4

**Platform:**
ubuntu-latest

**Runner type:**
Hosted

**Comment by MikeMcC399** [comment] 2022-10-18 09:48
- This is a duplicate of https://github.com/cypress-io/github-action/issues/613

**Comment by jpita** [comment] 2022-11-02 10:14
> * This is a duplicate of [Update `@actions/core` dependency to >=1.10.0 to avoid deprecation warning #613](https://github.com/cypress-io/github-action/issues/613)

close this as duplicate?

**Comment by nehal0412** [comment] 2022-11-03 09:40
Closing it as this is a duplicate ticket.

**Closed** 2022-11-03 09:42 UTC
