### ISSUE TITLE
Hard coded Node.js version

### ISSUE THREAD

**Issue by RobinKnipe** [cypress-io/github-action#489] opened 2022-01-23 14:01 UTC
The config in `action.yml` overrides any previously set node version (e.g. via `actions/setup-node`): https://github.com/cypress-io/github-action/blob/ffbc3616ae4754115d05d414810ff4a8e48fc6de/action.yml#L87

This causes failures if the project requires a more recent version, or it depends on a recent version of [@cypress/react >= v5.7.0](https://github.com/cypress-io/cypress/blob/5d1dce61e0641ceaaf1fd0b8153182869459715f/npm/react/CHANGELOG.md#cypressreact-v570-2021-05-12)

Ideally the action should use any version of node already available, or have a configuration switch to explicitly set the desired version (similar to `actions/setup-node`).

**Comment by rbayliss** [comment] 2022-01-25 16:33
I can second this issue. It seems to be happening because of [this commit](https://github.com/cypress-io/cypress/pull/18732/files#diff-97683c9a2857a02cef5d6db17bfc7c2bb6957e10b38b1f62dfc387c6031ea2f0R84), combined with the fact that this action uses the Cypress node API rather than executing it as a CLI command.

Not sure exactly how to fix this, but a temporary workaround seems to be adding a `command-prefix`, which [triggers invoking the tests with the CLI](https://github.com/cypress-io/github-action/blob/master/index.js#L623-L626). Eg:
```
- name: Cypress Tests
  uses: cypress-io/github-action@v2
  with:
    record: true
    command-prefix: "--"
```
This is a backdoor that ends up running a cypress command like: 
```
npx -- cypress run ...
```
Not sure what the side effects of this are (we're still testing it now), but I can confirm that when run this way, it invokes with the system node version rather than the action's node version.

**Comment by RobinKnipe** [comment] 2022-01-25 16:54
@rbayliss good shout. In case it's of interest, I found a similar workaround by explicitly adding a `command` config, even if it just does a basic cypress run, i.e. `command: npx cypress run` will also use a preconfigured node version.

**Comment by h2oearth** [comment] 2022-06-02 09:21
This issue is still present in Cypress 10:-(. I use Node 14.x, but some how cypress was falling back to Node 12.x

**Comment by willitsw** [comment] 2022-06-06 17:52
Also facing this issue with Cypress 10.

**Comment by einSelbst** [comment] 2022-06-25 22:48
@h2oearth @willitsw guys please check if you're using a container with an old node version. This is the case in the cypress github action example code.

>     container: cypress/browsers:node12.18.3-chrome87-ff82


Here is a list with the available node versions, up to node 17 as of today https://github.com/cypress-io/cypress-docker-images/tree/master/browsers

**Comment by MikeMcC399** [comment] 2022-12-05 16:09
This issue hasn't been addressed. It is not covered in the [README documentation](https://github.com/cypress-io/github-action#node-versions) and the workflow [.github/workflows/example-node-versions.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-node-versions.yml) doesn't notice the problem even though the only version of Node.js used is 16.13.0 despite the matrix definition `node: [14, 16, 18]`.

Are there any plans to fix this in any way, either by removing it as an option from the documentation or by making it work according to the documentation?

**Comment by MikeMcC399** [comment] 2023-07-11 16:21
@ricardo-dematos 

If you want to log your cucumber issue separately, we could take a look to see if there is some workaround which may be used.

There is an old comment in this issue from me which I wrote before I began to understand how the JavaScript action `github-action` worked. I have hidden that comment now, since it does not help so much.

GitHub has been asked to provide a later Node.js version after Node.js `16` (see https://github.com/orgs/community/discussions/58226) for JavaScript Actions to work with, however they have not yet responded with any concrete commitments. I would assume that if/when GitHub announces and releases updated support that there would be a new version of `github-action` released which would run under whatever GitHub provides (`18`? `20`?).

Probably this issue (https://github.com/cypress-io/github-action/issues/489) should be closed, because it is an architectural restriction of `github-action` being a GitHub JavaScript Action that the action's Node.js version is hard-coded. It is only Cypress itself which runs under this Node.js version. Other steps which are spawned by other options of `github-action` actually run under the runner's version of Node.js. Possibly we could make use of that for cucumber.

**Comment by MikeMcC399** [comment] 2023-07-11 18:24
@ricardo-dematos 

Using the github-action [command](https://github.com/cypress-io/github-action#custom-test-command) option, Cypress can be run using the Node.js version set up in the runner instead of `node16` specified by the JavaScript Action definition.

Please note however the restrictions described in the README for [command](https://github.com/cypress-io/github-action#custom-test-command), as this option by-passes many other options. It should give you a workaround for [badeball/cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) until GitHub provides a migration path to later Node.js versions.

If you have questions about this, I suggest moving to a separate issue for clarity.

**Comment by lmiller1990** [comment] 2023-07-12 22:25
I read through this issue. Is there something for us to do in our GH Action? It looks like you can choose the version from the ones GH supports. I'm not entirely clear if 18 is supported right now (conflicting info). If it is, you should be able to choose that one. If not, it would be blocked, but not by us.

**Comment by MikeMcC399** [comment] 2023-07-13 06:35
@lmiller1990 

> I read through this issue. Is there something for us to do in our GH Action? It looks like you can choose the version from the ones GH supports. I'm not entirely clear if 18 is supported right now (conflicting info). If it is, you should be able to choose that one. If not, it would be blocked, but not by us.

- One action would be to document the Node.js usage in the [README > Node.js Support](https://github.com/cypress-io/github-action/blob/master/README.md#nodejs-support) section. I have made a proposal in PR https://github.com/cypress-io/github-action/pull/961, which you are welcome to review. 
- Perhaps the document changes in the PR will also clear up your uncertainty about the support of Node.js `18`? `github-action@v5` can be called from a workflow environment set up for Node.js `18`. [![Node versions example](https://github.com/cypress-io/github-action/workflows/example-node-versions/badge.svg?branch=master)](.github/workflows/example-node-versions.yml) shows this working. This is currently the default version for GitHub-hosted runners. If Cypress is being run from `github-action@v5` in its default mode, then the [Cypress Module API](https://docs.cypress.io/guides/guides/module-api) call is made using the GitHub setting [runs.using](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions) `node16` for this action. This is currently the only version made available by GitHub for this purpose.

**Comment by lmiller1990** [comment] 2023-07-14 01:39
Looks like documenting this is the only actionable item here. Thanks for the PR!

**Comment by lmiller1990** [comment] 2023-07-14 01:40
Looks like we are at the mercy of GH to give us Node.js 18 in their actions. I think the PR doc clarifies; i don't see an other work to do at this point in time, so I will close this.

**Closed by lmiller1990** 2023-07-14 01:40 UTC

**Comment by lmiller1990** [comment] 2023-07-16 22:35
> which is less elegant and prone to issues #272 , #473 and #594 .

We can definitely accept a PR improving the GH Action! It looks like you tried but no luck. I also don't fully grok why that would fix / make us less prone to those issues.

> Error: The process '/opt/hostedtoolcache/node/18.16.1/x64/bin/npx' failed with exit code 2

I think exit code 2 is something to with failed dependencies installation.

We can re-open if you think there's a good path forward to properly resolving this.
