### ISSUE TITLE
Unable to run the cypress-io action when specifying a repo on the checkout

### ISSUE THREAD

**Issue by mechuser** [cypress-io/github-action#1190] opened 2024-05-29 18:16 UTC
Hi, 

I discovered that the cypress github actions is unable to run when we use the checkout action with the with option even if we specify the same repo as the one where the cypress actions tries to run.

Here is the workflow that was used in our test : 

- name: Checkout test-repo
   uses: actions/checkout@v4
   with:
      repository: placeholder-test-repo
      token: sample-token
      path: test-repo

- name: Tests execution 
   uses: cypress-io/github-actions@v6
   with:
      start: npx cypress-tags run -b chrome -e TAGS=\"JIRA-TICKET\"

Please note that this workflow uses placeholder values since i can't share certain values.

**Comment by MikeMcC399** [comment] 2024-05-30 04:23
@mechuser

The [start](https://github.com/cypress-io/github-action/blob/master/README.md#start-server) option is for starting a server. It is not intended to be used to run a command which executes Cypress tests.

You may be able to use the [command](https://github.com/cypress-io/github-action/blob/master/README.md#custom-test-command) option instead. If you attempt this, please make sure you read the documentation especially concerning the restrictions of this option.

If you believe you have found a bug in the action, you would need to submit debug logs (see [Debugging](https://github.com/cypress-io/github-action/blob/master/README.md#debugging)) and / or provide information which allows the issue to be easily reproduced.

Please note also that if you need to post `yaml` workflow code into an issue, you should be using triple backticks for fenced code blocks like this:

````
```yml
name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'master'
and so on
```
````

You can request community help on how to use Cypress from the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

**Comment by MikeMcC399** [comment] 2024-05-30 14:50
As discussed and resolved in https://discord.com/channels/755913899261296641/1245737842563354685, the second problem was the mismatch of directories. The `cypress-io/github-actions` needed to have its working-directory set to match `path: test-repo`.

The problems were caused by configuration.

**Closed by MikeMcC399** 2024-05-30 14:50 UTC
Labels: Needs Reproduction
