### ISSUE TITLE
Setting env variables breaks workflow

### ISSUE THREAD

**Issue by aniznik1** [cypress-io/github-action#217] opened 2020-10-28 10:52 UTC
I am trying to run Cypress tests with my local server on. Everything works great, except when I try to add environment variables to the runner:

```
jobs:
    cypress-run:
        runs-on: ubuntu-16.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  start: npm start
              env:
                  NODE_ENV: production

```

When `env` is present, I get the following error:

```
Run cypress-io/github-action@v2
Received 15073383 of 15073383 (100.0%), 20.2 MBs/sec
Cache Size: ~14 MB (15073383 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/463fd8d5-8e05-4725-a60a-d19b69ad7367/cache.tzst -P -C /home/runner/work/punched-static-content/punched-static-content
Received 58720256 of 174536160 (33.6%), 55.7 MBs/sec
Received 174536160 of 174536160 (100.0%), 92.0 MBs/sec
Cache Size: ~166 MB (174536160 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/656076d2-0074-4e0a-8e51-6003e64e4cc6/cache.tzst -P -C /home/runner/work/punched-static-content/punched-static-content
/usr/bin/yarn --frozen-lockfile
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.43s.
start server with command "npm start"
current working directory "/home/runner/work/punched-static-content/punched-static-content"
Error: Cannot find module 'cypress'
Require stack:
- /home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js
```

As you can see, the script fails because of `Error: Cannot find module 'cypress'`

I tried the same script but with with `uses: cypress-io/github-action@v1` and it works correctly, but I'd rather be using the latest release.

Any thoughts?

**Comment by bahmutov** [comment] 2020-10-28 12:34
Could you try:
- running with debugging turned on to see the extra messages and paste the entire log https://github.com/cypress-io/github-action#debugging
- bisect the released versions https://github.com/cypress-io/github-action/releases to find which version breaks it https://github.com/cypress-io/github-action#explicit-version

**Comment by bahmutov** [comment] 2020-11-13 19:59
Closing as cannot reproduce. Example actions with `env` parameter https://github.com/cypress-io/github-action/actions/runs/362228944 from https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-env.yml

**Closed by bahmutov** 2020-11-13 19:59 UTC
Labels: question

**Comment by aniznik1** [comment] 2020-11-18 08:32
@bahmutov I tried it again.

GitHub actions returns `Error: Cannot find module 'cypress'` when setting `NODE_ENV=production` in the actions file. This error does not trigger when any other environment variable is present.

**Comment by luisrudge** [comment] 2021-08-18 20:47
just a reference, NODE_ENV=production will make the `npm install` command ignore the devDependencies, which is probably where your cypress dependency is.
