### ISSUE TITLE
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync.

### ISSUE THREAD

**Issue by ricardo-dematos** [cypress-io/github-action#962] opened 2023-07-14 10:46 UTC
Since yesterday, 2023-07-13, when I resumed testing/using `cypress-io/github-action@v5`, I'm getting this error:

```
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

To be certain it's not related to our `package-lock.json`, I runned this workflow:

```yaml
      - name: 'Run end-to-end tests'
        id: cypress
        if: ${{ (success() || failure()) }}
        uses: cypress-io/github-action@v5  # see https://github.com/cypress-io/github-action/issues/620
        with:
          working-directory: 'e2e-tests'
          install: true
          runTests: false

      - name: 'Test package-lock.json'
        id: clean-install
        if: ${{ (success() || failure()) }}
        run: 'npm clean-install --no-fund --ignore-scripts --legacy-peer-deps --prefix "e2e-tests/"'
        shell: 'bash'
```

Here's the output:

![image](https://github.com/cypress-io/github-action/assets/108014795/583bb2eb-a311-42d9-b1aa-35de76242dc3)
![image](https://github.com/cypress-io/github-action/assets/108014795/cfbdea23-bb59-44dc-a3fb-73a01a11eaf5)
![image](https://github.com/cypress-io/github-action/assets/108014795/946ac41e-8a07-4d2c-a554-ace07ccfaa4f)

Could this be related with #958  ?

**Comment by MikeMcC399** [comment] 2023-07-14 11:31
@ricardo-dematos 

- This sounds similar to https://github.com/cypress-io/github-action/issues/922 which was caused by `legacy-peer-deps=true`

`github-action` simply executes `npm ci`

I notice in your additional test you are using `legacy-peer-deps=true`. Is this necessary for your repo? If yes, there are some different ways to work around this, so it would be good to know first about this dependency.

If you run something like the following, I expect that you will also see the error independently of `github-action`.

```
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: e2e-tests
```

> Could this be related with https://github.com/cypress-io/github-action/pull/958 ?

No. It is not related and the commit has not yet been merged into the `v5` branch which you are using.

**Comment by MikeMcC399** [comment] 2023-07-14 12:42
@ricardo-dematos 

I'm not sure that using `--ignore-scripts` as a general rule is a good idea as Cypress uses scripts to complete the installation locally. If you have solved your issue, then that is the main point.

> Please, feel free to close this issue.

This is something that you can do yourself. You should see a button at the bottom for this.

> As a final note, I suggest adding this to a FAQ / Common Problems page or as a Note when referring npm ci in the documentation.

There isn't in fact any FAQ for `github-actions`. For usage issues it's always good to search in the closed and open issues first. Also the Cypress technical community on Discord 
[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)
(click on button) is quite active to get peer advice.

The addition of an FAQ could certainly be considered.

**Closed** 2023-07-14 13:16 UTC
