### ISSUE TITLE
adding user 1001 throws EACCES permission issue

### ISSUE THREAD

**Issue by gkatsanos** [cypress-io/github-action#1175] opened 2024-05-03 14:43 UTC
I tried adding `      options: --user 1001` to ensure commit name / information are shown on my cypress cloud runs.
But doing so, throws an EACCES permission issue.

```yaml
jobs:
  cypress:
    runs-on: default-visable
    container:
      image: cypress/browsers:node-18.14.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
      options: --user 1001
    env:
      GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}
      PUBLIC_API_URL: "https://api.staging.visable.io"
      IS_CYPRESS: "true"
      BASE_URL: "https://www.wlw-staging.de"
      REQUESTS_INTERNAL_API: "https://requests-service.internal.wlw-1.staging.visable.cloud/requests_service/internal_api"
      RECAPTCHA_SITE_KEY: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
      RECAPTCHA_SECRET_KEY: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.3
      - name: Define proper Checkout REF
        shell: bash
        run: echo "ref=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF}})" >> $GITHUB_OUTPUT
        id: extract_ref
      - uses: actions/checkout@v4
        with:
          ref: "${{ steps.extract_ref.outputs.ref }}"
      - name: setup github packages authentication
        run: 'echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}" > ~/.npmrc'
      - uses: cypress-io/github-action@v6
        id: cypress
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}
          COMMIT_INFO_BRANCH: ${{ github.ref_name }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          build: pnpm build
          start: pnpm start
          browser: chrome
      - name: cleanup repo files
        if: always()
        run: find . -mindepth 1 -delete
```

![image](https://github.com/cypress-io/github-action/assets/1768834/16b69da0-d775-41c0-a836-d2d7f4e5e472)

I also tried to do what was suggested in https://github.com/cypress-io/github-action/issues/1129#issuecomment-1944303998 add options: --user 1001 but I get permissions issues.

**Comment by MikeMcC399** [comment] 2024-05-03 14:53
The [Docker image](https://github.com/cypress-io/github-action?tab=readme-ov-file#docker-image) section of the documentation says:

> Include `options: --user 1001` to avoid permissions issues.

This is missing from the workflow posted above.

**Comment by gkatsanos** [comment] 2024-05-08 12:39
sure, trying that just to make it clearer:

```yaml
jobs:
  cypress:
    runs-on: default-visable
    container:
      image: cypress/browsers:node-18.14.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
      options: --user 1001
    env:
      GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}
      PUBLIC_API_URL: "https://api.staging.visable.io"
      IS_CYPRESS: "true"
      BASE_URL: "https://www.wlw-staging.de"
      REQUESTS_INTERNAL_API: "https://requests-service.internal.wlw-1.staging.visable.cloud/requests_service/internal_api"
      RECAPTCHA_SITE_KEY: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
      RECAPTCHA_SECRET_KEY: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.3
      - name: Define proper Checkout REF
        shell: bash
        run: echo "ref=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF}})" >> $GITHUB_OUTPUT
        id: extract_ref
      - uses: actions/checkout@v4
        with:
          ref: "${{ steps.extract_ref.outputs.ref }}"
      - name: setup github packages authentication
        run: 'echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}" > ~/.npmrc'
      - uses: cypress-io/github-action@v6
        id: cypress
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}
          COMMIT_INFO_BRANCH: ${{ github.ref_name }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          build: pnpm build
          start: pnpm start
          browser: chrome
      - name: cleanup repo files
        if: always()
        run: find . -mindepth 1 -delete
```

ci output:

```
0s
Run pnpm/action-setup@v3
/usr/bin/docker exec  d7472bbeaff8694ddc8da[1](https://github.com/visable-dev/requests-frontend/actions/runs/9001862118/job/24728966119#step:3:1)641958f6af298fe18bad1f83ffbe64038a2fd1006f sh -c "cat /etc/*release | grep ^ID"
Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_c5aa5db7-4546-4d2d-95eb-fc1f342[16](https://github.com/visable-dev/requests-frontend/actions/runs/9001862118/job/24728966119#step:3:17)615'
    at Object.open (node:internal/fs/sync:78:18)
    at Object.openSync (node:fs:565:17)
    at Object.writeFileSync (node:fs:2288:35)
    at Object.appendFileSync (node:fs:2350:6)
    at Object.issueFileCommand (/__w/_actions/pnpm/action-setup/v3/dist/index.js:1:14731)
    at saveState (/__w/_actions/pnpm/action-setup/v3/dist/index.js:1:12889)
    at main (/__w/_actions/pnpm/action-setup/v3/dist/index.js:1:425)
    at 276 (/__w/_actions/pnpm/action-setup/v3/dist/index.js:1:539)
    at __nccwpck_require__ (/__w/_actions/pnpm/action-setup/v3/dist/index.js:10:243127)
    at /__w/_actions/pnpm/action-setup/v3/dist/index.js:10:243312 {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/__w/_temp/_runner_file_commands/save_state_c5aa5db7-4546-4d2d-95eb-fc1f34[21](https://github.com/visable-dev/requests-frontend/actions/runs/9001862118/job/24728966119#step:3:22)6615'
}
Error: Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_c5aa5db7-4546-4d2d-95eb-fc1f34216615'
```

**Comment by MikeMcC399** [comment] 2024-05-08 13:12
@gkatsanos 

- The issue about installing pnpm in your runner is a different one.
- It seems that you had a problem with this before, that you reported in https://github.com/cypress-io/github-action/issues/947

**Comment by gkatsanos** [comment] 2024-05-08 13:37
how do we proceed?

**Comment by gkatsanos** [comment] 2024-05-08 14:18
@MikeMcC399 coming back to this, it seems the permissions issue disappears when I remove:
```
          record: true
```
from the workflow. 

Shall I create a new issue or shall I modify the existing one?

**Comment by MikeMcC399** [comment] 2024-05-08 14:30
@gkatsanos 

This seems to be an ownership / permissions issue on your self-hosted runner `default-visable`

I tried to reproduce your problem on a GitHub-hosted runner `ubuntu-22.04` (with `options: --user 1001`) using latest versions and everything worked correctly.

Are you able to run a test of your workflow on `ubuntu-22.04`  instead of  `default-visable`?

**Comment by gkatsanos** [comment] 2024-05-08 14:32
I'm not a devops expert, but I'm pretty sure a generic ubuntu runner won't work in our infra. Our runners are not running inside docker by default. They are ephemeral EC2 instances with docker installed.

**Comment by gkatsanos** [comment] 2024-05-08 14:34
just in case I missed something, is there a documentation you can link with regards to how to display the commit name / or the branch name in the description of the cypress cloud run? I've read about different github env variables that should be passed but I may be forgetting something

**Comment by jennifer-shehane** [comment] 2024-05-08 14:55
@gkatsanos These are the docs for how we get git info for Cloud runs: https://docs.cypress.io/guides/continuous-integration/introduction#Git-information

**Comment by gkatsanos** [comment] 2024-05-08 16:43
I'm still not seeing the commit message as shown in the screenshot of the description of my issue. Any clues as to why?

**Comment by gkatsanos** [comment] 2024-05-08 16:45
I'm still not seeing the commit message as shown in the screenshot of the description of my issue. Any clues as to why? I'm using:

```
           COMMIT_INFO_MESSAGE: ${{ github.event.head_commit.message }}
```

**Comment by MikeMcC399** [comment] 2024-05-09 10:46
@gkatsanos 

> I'm not a devops expert, but I'm pretty sure a generic ubuntu runner won't work in our infra. Our runners are not running inside docker by default. They are ephemeral EC2 instances with docker installed.

I don't really understand this. Normally you would just change 

```yml
runs-on: default-visable
```

in your workflow to

```yml
runs-on: ubuntu-22.04
```

and GitHub Action takes care of the rest. But perhaps I am missing something fundamental here about your setup?

**Comment by gkatsanos** [comment] 2024-05-09 11:54
@MikeMcC399  ![image](https://github.com/cypress-io/github-action/assets/1768834/15581f39-8099-405d-a320-bff4b3954f26)

**Comment by gkatsanos** [comment] 2024-05-09 12:57
I was able to reproduce / fix the issue and it seems to be related to the runs-on value. 
I guess I need to see with our devops team if we could/should use the github public runners - maybe there's cost involved.

**Comment by gkatsanos** [comment] 2024-05-09 12:58
by the way, setting `record: true` occasionally hangs the test run, so I decided to not use it at all. Any clue if there's other documented similar issues?

**Comment by MikeMcC399** [comment] 2024-05-09 14:04
@gkatsanos 

If your workflow runs successfully on a GitHub-hosted runner and it fails on a self-hosted runner then you would need to look at how your self-hosted runner is set up. Unfortunately that is out-of-scope for this Cypress GitHub Actions repo to provide any specific information about self-hosted runners. The GitHub documentation [About self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners) appears not to cover the subject of directory ownership and permissions. The topic generally only becomes a problem when a Docker image is run inside a runner.  You can find a mention of a related issue in the [cypress-docker-images README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#firefox-not-found) where it notes:

> The [GitHub Actions Runner](https://github.com/actions/runner) creates the `/github/home` (`$HOME`) directory with non-root ownership `1001` (`runner`).

**Comment by MikeMcC399** [comment] 2024-05-09 14:10
@gkatsanos 

> by the way, setting `record: true` occasionally hangs the test run, so I decided to not use cypress cloud after all. Any clue if there's other documented similar issues?

This is a different topic and generally it is not something which the Cypress GitHub Action has any influence on.

Cypress Cloud has its own [different support channel](https://www.cypress.io/support) which is open to customers on paid plans.

Community support is available independent of whether you use the Free plan or one of the paid plans. You can access this through [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button). If you want to discuss your issue on Discord be prepared to provide more details about configuration, versions, where it hangs, how it hangs, etc. otherwise the question is too vague to give any meaningful response.

**Comment by gkatsanos** [comment] 2024-05-09 14:17
> @gkatsanos
> 
> > by the way, setting `record: true` occasionally hangs the test run, so I decided to not use cypress cloud after all. Any clue if there's other documented similar issues?
> 
> This is a different topic and generally it is not something which the Cypress GitHub Action has any influence on.
> 
> Cypress Cloud has its own [different support channel](https://www.cypress.io/support) which is open to customers on paid plans.
> 
> Community support is available independent of whether you use the Free plan or one of the paid plans. You can access this through [![Discord chat](https://camo.githubusercontent.com/15800a9ae6e0c62d3c4862d3300f6cf3423fee1112a6bbac2a2e51469dd47649/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f636861742d6f6e253230446973636f72642d627269676874677265656e)](https://on.cypress.io/discord) (click on button). If you want to discuss your issue on Discord be prepared to provide more details about configuration, versions, where it hangs, how it hangs, etc. otherwise the question is too vague to give any meaningful response.

thank you. I'm not sure the product offering is such that deserves any more investment in time. I was merely evaluating it.

I'll try to see what's wrong with the self-hosted runners though as this might be a blocker down the line.

**Comment by MikeMcC399** [comment] 2024-05-14 11:57
Closing this issue now as the permissions issue on the GitHub self-hosted runner `default-visable` is not something which can be solved by changes to the Cypress GitHub Action.

**Closed by MikeMcC399** 2024-05-14 11:57 UTC
Labels: ci
