### ISSUE TITLE
Facing issue with Jenkins pipe line setup.

### ISSUE THREAD

**Issue by akaturi1** [cypress-io/github-action#780] opened 2023-02-09 13:24 UTC
Below is the error I got in the Jenkins console:
---------------------------------------------------
**It looks like this is your first time using Cypress: 12.5.1

[STARTED] Task without title.
[SUCCESS] Task without title.

Opening Cypress...
[654:0209/131501.287696:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
There is a cypress.json file at the path: /home/jenkins/workspace/../Smoke

Cypress version 10.0.0 no longer supports cypress.json.

Please run cypress open to launch the migration tool to migrate to cypress.config.{js,ts,mjs,cjs}.**
-------------------------------------------------------------------------------------------------------------
But I installed in my Docker Component:
Installing **Cypress (version: 8.7.0)**

[STARTED] Task without title.
[SUCCESS] Task without title.
[STARTED] Task without title.
[SUCCESS] Task without title.
[STARTED] Task without title.
[SUCCESS] Task without title.
You can now open Cypress by running: node_modules/.bin/cypress open

Below are the versions installed:
git --version # 'git version 1.8.3.1'
+ npm --version
6.14.16
+ node --version
v14.19.0

Below are the commands I used to install dependencies:
                        npm --version
                        node --version
                        npm ci --registry
                        npm i cypress@8.7.0
                        npm cypress -v

and below is the command used to run my spec:
npx cypress run --spec ../../../file_name.js

My code is also written in 8.7.0 and it cloned properly to Docker from GitHUB.
But when I am running one of my test case using above mentioned command I am getting the above error.

Can you please suggest to resolve this without upgrading my Cypress version, thank you.!

**Comment by MikeMcC399** [comment] 2023-02-09 14:02
@akaturi1 

This is a repository for `uses: cypress-io/github-action` and I don't see that referred to anywhere in your description.

I'm unsure if you are in the right place with your issue. Are you using a GitHub action like in the [README basic example](https://github.com/cypress-io/github-action#basic)?

```yml
name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
```

---

Apart from that, it seems that the clue is in the first line of your posting:

`
**It looks like this is your first time using Cypress: 12.5.1
`

which shows that Cypress 12.5.1 (the latest version) is running and not the version 8.7.0 which you are expecting to run.

**Comment by akaturi1** [comment] 2023-02-09 14:40
Thank you Mike.!

I am trying to setup Jenkins pipeline for my code in GitHub using Docker. 

and I intentionally mentioned 8.7.0 in  my Jenkins file to install in my docker image. And it showing installed, still throwing error.

Please suggest If any place to get some suggestions to resolve this issue.

**Comment by MikeMcC399** [comment] 2023-02-09 14:49
@akaturi1 

I think you confirmed that you are not using `cypress-io/github-action`. I'm sorry that I am not really very familiar with Jenkins and this is not the right place to be discussing it.

You might try 

- https://community.jenkins.io/

`cypress-io/github-action` works in conjunction with [Cypress Cloud](https://www.cypress.io/cloud/) for recording tests and viewing in a console.

**Comment by MikeMcC399** [comment] 2023-02-09 18:46
Apart from that you should probably just check whatever `package.json` files you have in your environment and make sure that they have the required version of cypress in them.

**Comment by MikeMcC399** [comment] 2023-02-28 17:11
@akaturi1 

Were you able to resolve your issue?

**Comment by MikeMcC399** [comment] 2023-04-10 12:15
I suggest to close this issue now, since it is stale.

**Comment by nagash77** [comment] 2023-04-10 12:58
Hi @akaturi1 , I am going to close this issue since it does not appear to be related to Cypress.  I would suggest you check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Closed by nagash77** 2023-04-10 12:58 UTC
