### ISSUE TITLE
Error: The process '/usr/local/bin/npx' failed with exit code 1

### ISSUE THREAD

**Issue by stoplion** [cypress-io/github-action#211] opened 2020-10-23 22:29 UTC
Using version 5.4.0 Cypress

Getting a ..
`Error: The process '/usr/local/bin/npx' failed with exit code 1`

**Comment by bahmutov** [comment] 2020-10-23 22:45
Could you provide any more details? Maybe enable debugging and post the logs ? Maybe a link to the action run?

**Comment by andersravn** [comment] 2020-10-27 12:58
We are also experiencing this today. These are the logs:
```
Run cypress-io/github-action@v2
/usr/bin/yarn --frozen-lockfile
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.30s.
/usr/local/bin/npx cypress verify
The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /home/runner/.cache/Cypress/5.0.0/Cypress/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /home/runner/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/runner/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error

----------

Platform: linux (Ubuntu - 18.04)
Cypress Version: 5.0.0
Error: The process '/usr/local/bin/npx' failed with exit code 1
```

Looking at the changes we've made since Friday, where it last worked, I don't expect it to be something on our end. I'll try to double-check.

**Comment by miohtama** [comment] 2020-10-28 13:37
I am not sure if related but starting to see "cannot run binary errors" as well very recently.

`(node:28066) UnhandledPromiseRejectionWarning: Error: There was an error when attempting to execute the process '/usr/local/bin/npm'. This may indicate the process failed to start. Error: spawn /usr/local/bin/npm ENOENT`

With the following receipt

```
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: ./frontend_new
        build: npm run build:testing
        start: npm run start:integration-test-server
        record: true
      env:
        CI: true
        # pass the Dashboard record key as an environment variable
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
```

Almost looks like `PATH` or `/usr/bin` is destroyed between `build` and `start` steps. 

Still diagnosing the issue.

**Comment by bausmeier** [comment] 2020-10-28 13:42
We're seeing the exact same error as @miohtama, except with yarn instead of npm. Haven't managed to do any further digging.

Our config is:

```yaml
- name: Install dependencies
  run: yarn install --frozen-lockfile
- name: Check formatting
  run: yarn run format:check
- name: Run Cypress
  uses: cypress-io/github-action@v2
  with:
    working-directory: web
    install: false
    start: yarn serve
```

**Comment by miohtama** [comment] 2020-10-28 14:03
It is a regression in Cypress action. I do not know what or where.

I fixed by pinning down Cypress action to an earlier version:

```
    - name: Cypress run
      uses: cypress-io/github-action@v2.2.7
```

**Comment by bahmutov** [comment] 2020-10-28 14:22
The explicit version pin by is a good solution for now

Can someone run with https://github.com/cypress-io/github-action#debugging flags on and paste the full log up to the error? I wonder if the new caching does not restore the caches correctly and thus fails to run.

**Comment by andersravn** [comment] 2020-10-28 14:57
These are the full logs:

```
##[debug]Evaluating condition for step: 'Run Cypress tests'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run Cypress tests
##[debug]Loading inputs
##[debug]Loading env
Run cypress-io/github-action@v2
##[debug]using custom Cypress cache folder "/home/runner/.cache/Cypress"
##[debug]trying to restore cached NPM modules
##[debug]Resolved Keys:
##[debug]["yarn-linux-x64-aec53dd3b6aac2e7a22939bba0e5544fd1627c47da090ee55424ff1b611e431577f779508b0f286f061e48b3d4276595892aabd617b42223280322a2d5c04ab9","yarn-linux-x64-aec53dd3b6aac2e7a22939bba0e5544fd1627c47da090ee55424ff1b611e431577f779508b0f286f061e48b3d4276595892aabd617b42223280322a2d5c04ab9"]
##[debug]Checking zstd --version
##[debug]trying to restore cached Cypress binary
##[debug]Resolved Keys:
##[debug]["cypress-linux-x64-aec53dd3b6aac2e7a22939bba0e5544fd1627c47da090ee55424ff1b611e431577f779508b0f286f061e48b3d4276595892aabd617b42223280322a2d5c04ab9","cypress-linux-x64-"]
##[debug]Checking zstd --version
##[debug]*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***
##[debug]Resource Url: https://artifactcache.actions.githubusercontent.com/unXnoT28Ujd51XGkHKvRiknbRjBHSINEuQHH9ZKiLa70N5bhjm/_apis/artifactcache/cache?keys=yarn-linux-x64-aec53dd3b6aac2e7a22939bba0e5544fd1627c47da090ee55424ff1b611e431577f779508b0f286f061e48b3d4276595892aabd617b42223280322a2d5c04ab9%2Cyarn-linux-x64-aec53dd3b6aac2e7a22939bba0e5544fd1627c47da090ee55424ff1b611e431577f779508b0f286f061e48b3d4276595892aabd617b42223280322a2d5c04ab9&version=db8d7573c9c1e018880f416d1266a74a2aca6c42332d4f92d877cf07990531be
##[debug]*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***
##[debug]Resource Url: https://artifactcache.actions.githubusercontent.com/unXnoT28Ujd51XGkHKvRiknbRjBHSINEuQHH9ZKiLa70N5bhjm/_apis/artifactcache/cache?keys=cypress-linux-x64-aec53dd3b6aac2e7a22939bba0e5544f286f061e48b3d4276595892aabd617b42223280322a2d5c04ab9%2Ccypress-linux-x64-&version=1955096f8dd0181bc182356f3b1a36196
##[debug]npm cache hit undefined
##[debug]cypress cache hit undefined
##[debug]installing NPM dependencies using Yarn
##[debug]yarn at "/usr/bin/yarn"
/usr/bin/yarn --frozen-lockfile
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.40s.
##[debug]Verifying Cypress
/usr/local/bin/npx cypress verify
The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /home/runner/.cache/Cypress/5.0.0/Cypress/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /home/runner/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/runner/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error

----------

Platform: linux (Ubuntu - 18.04)
Cypress Version: 5.0.0
##[debug]The process '/usr/local/bin/npx' failed with exit code 1
##[debug]Error: The process '/usr/local/bin/npx' failed with exit code 1
##[debug]    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:1293:25)
##[debug]    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:1276:18)
##[debug]    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:1170:27)
##[debug]    at ChildProcess.emit (events.js:210:5)
##[debug]    at maybeClose (internal/child_process.js:1021:16)
##[debug]    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Error: The process '/usr/local/bin/npx' failed with exit code 1
##[debug]Node Action run completed with exit code 1
##[debug]CI='1'
##[debug]CYPRESS_CACHE_FOLDER='/home/runner/.cache/Cypress'
##[debug]CYPRESS_CACHE_FOLDER='/home/runner/.cache/Cypress'
##[debug]Finishing: Run Cypress tests
```

I modified the "keys" in there because I wasn't sure if they were secret.

**Comment by bahmutov** [comment] 2020-10-28 15:23
Hmm, so weird, this is working in all examples in https://github.com/bahmutov/cypress-gh-action-example

Does anyone have a public repo showing the problem?

@andersravn what the version of Cypress specified in the package.json file? Is it exact or does it use `~` or `^` or `*` range by any chance?

**Comment by bahmutov** [comment] 2020-10-28 15:43
@andersravn can you post your full workflow file, I wonder if there is something else going, and if it does not actually install Cypress binary while doing `yarn` command

**Comment by hrgui** [comment] 2020-10-28 15:46
I have the same problem except with yarn. yarn install works.

```
(node:2922) UnhandledPromiseRejectionWarning: Error: There was an error when attempting to execute the process '/usr/bin/yarn'. This may indicate the process failed to start. Error: spawn /usr/bin/yarn ENOENT
```

I'll see if I can repo this in a public repo, since the error is in a private repo.

**Comment by hrgui** [comment] 2020-10-28 17:18
@bahmutov  I was able to reproduce the error with a public version here:

https://github.com/hrgui/cypress-lerna-example/runs/1322135919

**Comment by bahmutov** [comment] 2020-10-28 19:34
@hrgui I am trying to recreate the error and still fail. Can you try v2.3.5 please?

**Comment by bahmutov** [comment] 2020-10-28 19:54
Interesting, I just recreated it in this workflow, similar to your @hrgui where the install happens in the root folder, while we try to run using `yarn` from the subfolder https://github.com/bahmutov/cypress-gh-action-example/runs/1322897555?check_suite_focus=true

```yml
name: subfolder
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # first, install dependencies and Cypress
      # from the root folder using the lock file
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      # now run the tests from the subfolder
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: packages/e2e
          start: yarn start-server
```

**Comment by bahmutov** [comment] 2020-10-28 20:15
This is so weird. There are definitely both tools

<img width="682" alt="Screen Shot 2020-10-28 at 4 14 06 PM" src="https://user-images.githubusercontent.com/2212006/97491536-add1c180-1938-11eb-905b-b11cbb411e2a.png">

When just printing npm or yarn version from subfolder, it fails

```
- name: Cypress run
  uses: cypress-io/github-action@v2
  with:
    install: false
    working-directory: packages/e2e
    start: npm --version
```

<img width="1047" alt="Screen Shot 2020-10-28 at 4 15 27 PM" src="https://user-images.githubusercontent.com/2212006/97491645-d1950780-1938-11eb-9568-d8d6f788c643.png">

**Closed** 2020-10-28 20:28 UTC
Labels: bug, question

**Comment by hrgui** [comment] 2020-10-28 22:05
Thanks @bahmutov 

Confirmed it's working in https://github.com/hrgui/cypress-lerna-example/runs/1323455193

and https://github.com/hrgui/cypress-lerna-example/pull/3

**Comment by Tonyfilho** [comment] 2023-12-06 16:59
hello a solved the problem when i remove from  gitIgnore the folder dist/    i am using Angular with firebase hosting

**Comment by exiguus** [comment] 2025-01-05 23:09
Adding "engines" to package.json will fix the issue:
```json
  "engines": {
    "pnpm": ">=9.0.0 <11.0.0",
    "npm": ">=10.0.0 <11.0.0",
    "node": ">=22.0.0 <23.0.0"
  }
  ```

**Comment by KseniyaTsypunova** [comment] 2025-05-21 06:33
In case anyone facing this is 2025 - updating cypress-axe to latest helped me. 
I upgraded cy version to 14.3.3 and got Error: The process '/usr/local/bin/npx' failed with exit code 1
then upgraded axe and tests started working
