### ISSUE TITLE
Unable to process command set-env name=CYPRESS_CACHE_FOLDER

### ISSUE THREAD

**Issue by valentinogagliardi** [cypress-io/github-action#268] opened 2020-12-18 17:37 UTC
First of all thanks for this action! This is my first time with this action, not sure if it was working before, but I got the following error in GA:

```text
Error: Unable to process command '::set-env name=CYPRESS_CACHE_FOLDER::/home/runner/.cache/Cypress' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::set-env name=TERM::xterm' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

To avoid breaking CI I had to add `ACTIONS_ALLOW_UNSECURE_COMMANDS` to the list of environment variables.

**Comment by bahmutov** [comment] 2020-12-18 17:46
Duplicate of https://github.com/cypress-io/github-action/issues/206 - released in v2.3.1 I suggest you use `cypress-io/github-action@v2` in general

**Closed by bahmutov** 2020-12-18 17:46 UTC
