### ISSUE TITLE
[Bug] CI component tests under CI MS Windows OS fails with error message Cypress failed to make a connection to Firefox

### ISSUE THREAD

**Issue by tmszi** [cypress-io/github-action#988] opened 2023-08-08 04:46 UTC
**Describe the bug**
CI component tests under CI MS Windows OS (windows-latest) fails with error message _Cypress failed to make a connection to Firefox_.

**To Reproduce**

1. Setup GitHub [repo workflow file](https://github.com/auto-mat/ride-to-work-by-bike-frontend/actions/runs/5788804118/workflow) Cypress CI tests (component/e2e) with MS Windows OS (windows-latest)
2. GitHub repo actions cache is deleted
3. Trigger GitHub [repo action](https://github.com/auto-mat/ride-to-work-by-bike-frontend/actions/runs/5788804118/job/15688729905#step:5:992) with push commit

```
cypress:server:cypress exiting with err Error: connect ECONNREFUSED 127.0.0.1:50051
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
 {
  isCypressErr: true,
  type: 'FIREFOX_COULD_NOT_CONNECT',
  details: 'Error: connect ECONNREFUSED 127.0.0.1:50051\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)\n',
  messageMarkdown: 'Cypress failed to make a connection to Firefox.\n' +
    '\n' +
    'This usually indicates there was a problem opening the Firefox browser.',
  originalError: OperationalError: connect ECONNREFUSED 127.0.0.1:50051
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
   {
    cause: Error: connect ECONNREFUSED 127.0.0.1:50051
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
     {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 50051
    },
    isOperational: true,
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 50051
  },
  stackWithoutMessage: '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)\n'
} +1m
Cypress failed to make a connection to Firefox.

This usually indicates there was a problem opening the Firefox browser.

Error: connect ECONNREFUSED 127.0.0.1:50051
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
```

Full GitHub Cypress action CI [debug log](https://github.com/auto-mat/ride-to-work-by-bike-frontend/actions/runs/5788804118/job/15688729905#step:5:992).

**Expected behavior**
CI component tests under CI MS Windows OS (windows-latest) should passed same as under other CI OS platforms GNU/Linux (ubuntu-latest), Mac OS (macos-latest).

**System description:**

Node.js: v18.17.0
Cypress: 10.10.0
CI OS: windows-latest
GitHub Cypress action: cypress-io/github-action@v5 

**Additional context**
CI component tests under other CI OS platforms GNU/Linux (ubuntu-latest), Mac OS (macos-latest) [normally passed too](https://github.com/auto-mat/ride-to-work-by-bike-frontend/actions/runs/5786190367). Component/e2e tests under local MS Windows OS normally passed too.

**Comment by MikeMcC399** [comment] 2023-08-08 07:44
@tmszi 

Thanks for your issue report! You did a great job to present all the information necessary!

I can partially reproduce this using current versions. Cypress `12.17.3` has difficulty connecting to Mozilla Firefox `115` with e2e and component testing, on `ubuntu-22.04` and `windows-2022` in a GitHub Actions environment. After a certain number of attempts, Cypress does however manage to connect. This is different to your experience where it fails to connect.

| OS           | test type | attempts | log                                                                                                |
| ------------ | --------- | -------- | -------------------------------------------------------------------------------------------------- |
| windows-2022 | component | 30/62    | [15702082167](https://github.com/MikeMcC399/github-action/actions/runs/5793754610/job/15702082167) |
| ubuntu-22.04 | component | 20/62    | [15702082023](https://github.com/MikeMcC399/github-action/actions/runs/5793754610/job/15702082023) |
| ubuntu-22.04 | e2e       | 21/62    | [15677583643](https://github.com/cypress-io/github-action/actions/runs/5785268746/job/15677583643) |

I also tried to reproduce this locally with Cypress `12.17.3` on Windows 11 with Firefox `116` using [examples/component-tests](https://github.com/cypress-io/github-action/tree/master/examples/component-tests) and there was no problem to connect to Firefox. I could not test this with the older Cypress `10.10.0` since it is not compatible with the newer Framework versions used in the examples and it immediately fails.

Also, according to the [Cypress Changelog 11.0.0](https://docs.cypress.io/guides/references/changelog#11-0-0), the version `11.0.0` was the first version to state "Component Testing is now generally available for projects using React, Next.js, Angular, and Vue!", so version `10.10.0` is not covered for component testing.

## Suggestions

1. You are using Cypress `10.10.0` with component testing. You may like to consider updating to at least Cypress `11.x`, if not `12.x`.
2. If updating to Cypress `12` does not fix the problem connecting to Firefox, then the issue would need to be investigated by the Cypress core team as `cypress-io/github-action` does not have any influence on the way that Cypress connects to Firefox.
3. Your [workflow](https://github.com/auto-mat/ride-to-work-by-bike-frontend/actions/runs/5788804118/workflow) shows `command: npx cypress run --component --browser firefox` which essentially duplicates some other parameters you have chosen. See [README > Custom test command](https://github.com/cypress-io/github-action#custom-test-command). `cypress-io/github-action@v5` automatically runs Cypress tests without needing a Custom test command. I suggest to remove the `command:` line and use only the `component` and `browser` parameters, which you have already defined. I don't expect this to improve the outcome for Firefox. It just cleans up the workflow.

**Comment by nagash77** [comment] 2023-08-08 12:39
@tmszi thank you for opening this issue.  @MikeMcC399 thank you for the great troubleshooting!  As Mike indicated, it appears you are running on an old version of Cypress.  Can you verify that the problem is still happening when you upgrade to the latest Cypress?

**Comment by tmszi** [comment] 2023-08-08 13:39
@MikeMcC399 @nagash77 Thanks for your quick response and suggestions! Upgrade Cypress package to version 11.0.0 or latest 12.17.3 version fixed reported issue.

**Comment by MikeMcC399** [comment] 2023-08-09 16:09
@tmszi 

It's good to hear that upgrading Cypress resolved your issue! Would you like to close this issue now? You should see a button at the bottom to do this.

**Closed** 2023-08-09 17:26 UTC
