### ISSUE TITLE
Intermittent EPIPE write failure uploading media

### ISSUE THREAD

**Issue by michael1visser** [cypress-io/github-action#1060] opened 2023-10-18 13:23 UTC
In the past several months we have seen intermittent failures of cypress container test runs because of an error related to uploading videos and images. All tests pass but the container fails the test run fails because of the error. 

It does not always fail on the same test file, nor does there appear to be any specific pattern to the failures. We'll see several in a day or week, and then none for the following week. 

```
write EPIPE
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writevGeneric (node:internal/stream_base_commons:143:3)
    at Socket._writeGeneric (node:net:815:11)
    at Socket._writev (node:net:824:8)
    at doWrite (node:internal/streams/writable:406:12)
    at clearBuffer (node:internal/streams/writable:561:5)
    at Writable.uncork (node:internal/streams/writable:348:7)
    at p.sendFrame (<embedded>:2404:495920)
    at p.dispatch (<embedded>:2404:495107)
    at p.send (<embedded>:2404:494940)
    at A.send (<embedded>:2404:505537)
    at _._enqueueCommand (<embedded>:2404:525846)
    at <embedded>:2404:523361
    at new Promise (<anonymous>)
    at _.send (<embedded>:2404:523335)
    at k.send [as sendDebuggerCommandFn] (<embedded>:4557:77430)
    at _.<anonymous> (<embedded>:4557:50879)
    at _.emit (node:events:527:28)
    at _._handleMessage (<embedded>:2404:525699)
    at A.<anonymous> (<embedded>:2404:525307)
    at A.emit (node:events:527:28)
    at g.U (<embedded>:2404:510587)
    at g.emit (node:events:527:28)
    at g.dataMessage (<embedded>:2404:490962)
    at <embedded>:2404:490494
    at <embedded>:2404:481816
    at <embedded>:2404:482768
    at afterWrite (node:internal/streams/writable:497:5)
    at onwrite (node:internal/streams/writable:477:7)
    at Zlib.cb (node:internal/streams/transform:202:7)
    at Zlib.processCallback (node:zlib:611:8)
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

our setup in the action is as follows:

```
jobs:
  cypress-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2,3,4,5]
      services:
           etc....
```

```
steps
    - name: Cypress run
          uses: cypress-io/github-action@v4
          with:
              start: yarn start:e2e
              wait-on: 'http://localhost:3000'
              wait-on-timeout: 200
              record: true
              parallel: true
          env:
             <our_variables>
```
Please let me know if you need anything else to troubleshoot.

**Comment by MikeMcC399** [comment] 2023-10-18 13:40
@michael1visser 

Are you able to update to `cypress-io/github-action@v6` which uses `node20`? That would be the first change to try out. `cypress-io/github-action@v4` is no longer supported since it relies on `node16` which has passed into end-of-life.

You might also want to consider updating to `ubuntu-22.04` at the same time, since I would expect that the 3.5 year old `ubuntu-20.04` will also reach its end-of-life on GitHub early next year.

Which version of Cypress are you using?

**Comment by michael1visser** [comment] 2023-10-19 09:45
> Which version of Cypress are you using?

we're on 12.16.0

**Comment by michael1visser** [comment] 2023-10-19 12:41
@MikeMcC399 updated everything as you suggested, ubuntu to 22.04, node to 20, cypress action to v6. Got an EPIPE failure on one of the containers on the first run. The error is the same as the one posted above

**Comment by MikeMcC399** [comment] 2023-10-19 14:04
@michael1visser

> updated everything as you suggested, ubuntu to 22.04, node to 20, cypress action to v6. Got an EPIPE failure on one of the containers on the first run. The error is the same as the one posted above

Thanks for carrying out the suggested updates!

The error
> Error: write EPIPE

has been reported previously against Cypress in several issues, and some root causes are supposed to be fixed.

The last report of the issue was in the following, although the root cause in your case may not necessarily be the same:

- https://github.com/cypress-io/cypress/issues/26740

You wrote that you are currently using `cypress@12.6.0`. If you are still able to reproduce the issue using the latest version of Cypress (currently `13.3.2`) then the issue could be transferred to the https://github.com/cypress-io/cypress/issues list. It is not a problem caused by `github-action` as such, so it is not something which can be fixed by making changes to the action.

Note that Cypress `13.x` disables video generation by default (see [Migration Guide > Migrating to Cypress 13.0 > Video updates](https://docs.cypress.io/guides/references/migration-guide#Video-updates)) and if your issue is made related to video generation, then upgrading may be sufficient to stop the issue happening.

I couldn't find any other workaround listed for the issue.

**Comment by MikeMcC399** [comment] 2023-11-04 07:07
@michael1visser 

Have you been able to test with the latest Cypress `13.x` version?

**Comment by MikeMcC399** [comment] 2023-11-07 11:47
Closing.

If there is up-to-date test data available, we can re-open.

**Closed by MikeMcC399** 2023-11-07 11:47 UTC
Labels: bug, Cypress Cloud
