### ISSUE TITLE
I'm not able to run Cypress Tests on Self Hosted Runner

### ISSUE THREAD

**Issue by mchittineni** [cypress-io/github-action#1307] opened 2024-11-15 10:36 UTC
We are not able to run Cypress tests in our self hosted runner

This is our Action Workflow File

```
  cypress-run:
    needs: InitiateRunner
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Initialize Node
        run: npm install
             
      - name: Update Packages
        run: npm ci

      - name: Setup Google Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-dependencies: true

      - name: Chrome Version Check
        run: |
          ${{ steps.setup-chrome.outputs.chrome-path }} --version  

      - name: Cypress Install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
        env: 
          DEBUG: '@cypress/github-action'

      - name: Cypress Info
        run: npx cypress info

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        timeout-minutes: 60
        with:
          quiet: true
          command: npm run cy:run:chrome
        env: 
          DEBUG: '@cypress/github-action'

      - name: Create Markdown
        timeout-minutes: 60
        if: always()
        run: |
          npm install winston commander mustache
          node convert.js -p  cypress/reports/html/index.json -t results-template.md -o output.md
          cat output.md >> $GITHUB_STEP_SUMMARY

      - name: Archive Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build artifacts
          path: |
            cypress/reports/html/index.html
            cypress/screenshots
            cypress/videos
            cypress/reports
```

And this is our Cypress Config File

```
const { defineConfig } = require('cypress')
const tasks = require('./cypress/support/tasks/tasks')

module.exports = defineConfig({
  reporter: 'cypress-mochawesome-reporter',
  video: true,
  videoCompression: 15,
  reporterOptions: {
    reportDir: 'cypress/reports/html',
    reportTitle: 'API Tests',
    code: true,
    charts: true,
    embeddedScreenshots: true,
    inlineAssets: true,
    saveJson: true
  },
  experimentalMemoryManagement: true,
  e2e: {
    specPattern: 'cypress/e2e/*.cy.js',
    experimentalStudio: true,
    experimentalModifyObstructiveThirdPartyCode: true,
    chromeWebSecurity: false,
    requestTimeout: 15000,
    responseTimeout: 15000,
    taskTimeout: 30000,
    setupNodeEvents(on, config) {
      require('cypress-mochawesome-reporter/plugin')(on)
      require('@cypress/grep/src/plugin')(config)
      on('before:browser:launch', (browser, launchOptions) => {
        console.log('Launching browser:', browser.name)
        if (browser.name === 'chrome') {
          launchOptions.args.push('--disable-gpu')
          launchOptions.args.push('--window-size=1920,1080')
          console.log('Chrome launch options:', launchOptions)
          return launchOptions
        }
      })
      on('task', {
        log(message) {
          console.log(message)
          return null
        }
      })
    },
    supportFile: false,
    video: false
  }
})

```

I have installed all the prerequisite packages using the Dockerfile 

```
# Base image
FROM ubuntu:22.04

# Environment variables
ENV RUNNER_ALLOW_RUNASROOT=true
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
ENV RUNNER_VERSION=2.320.0

# Update system and install required packages
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
	curl \
	fonts-liberation \
	git \
	gnupg \
	iputils-ping \
	jq \
	libasound2 \
	libasound2-dev \
	libatk1.0-0 \
	libatk-bridge2.0-0 \
	libc6 \
	libcups2 \
	libcurl4 \
	libdbus-1-3 \
	libgconf-2-4 \
	libgbm1 \
	libgbm-dev \
	libgdk-pixbuf2.0-0 \
	libgdk-pixbuf-2.0-0 \
	libnspr4 \
	libgtk-3-0 \
	libgtk2.0-0 \
	libicu-dev \
	libnotify-dev \
	libnss3 \
	libnss3-dev \
	libpangocairo-1.0-0 \
	libu2f-udev \
	libx11-6 \
	libx11-xcb1 \
	libxcomposite1 \
	libxcursor1 \
	libxdamage1 \
	libxext6 \
	libxrandr2 \
	libxshmfence1 \
	libxss1 \
	libxss-dev \
	libxtst6 \
	unzip \
	xauth \
	xvfb \
	xdg-utils \
	xz-utils \
	binutils \
	sudo && \
    rm -rf /var/lib/apt/lists/*
# Clean up cache to reduce image size

# Install GitHub CLI
RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && \
    chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
    tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
    apt update && apt install -y gh && \
    rm -rf /var/lib/apt/lists/*

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && ./aws/install && rm -rf awscliv2.zip aws

# Set up GitHub Actions Runner
RUN mkdir /github-action-runner && cd /github-action-runner && \
    curl -O -L https://github.com/actions/runner/releases/download/v$RUNNER_VERSION/actions-runner-linux-x64-$RUNNER_VERSION.tar.gz && \
    tar xzf ./actions-runner-linux-x64-$RUNNER_VERSION.tar.gz && \
    rm ./actions-runner-linux-x64-$RUNNER_VERSION.tar.gz

# Create ubuntu user with sudo privileges for ubuntu:24.04
# RUN id -u ubuntu &>/dev/null || useradd -m -s /bin/bash ubuntu && \
#     echo "ubuntu:docker" | chpasswd && \
#     echo "ubuntu ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
#     ldconfig

# Create ubuntu user
RUN useradd -m -s /bin/bash ubuntu && \
    echo "ubuntu:docker" | chpasswd && \
    echo "ubuntu ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    ldconfig

# Set the working directory
WORKDIR /github-action-runner

# Copy and set permissions for the script
COPY script.sh .
RUN chmod +x script.sh

# Define the default command
CMD ["./script.sh"]
```

Even though Chrome was successfully installed

![Screenshot 2024-11-15 at 10 26 11](https://github.com/user-attachments/assets/c1b7f8ce-43d8-4924-ac5a-f99f7ae31f10)

Cypress is not able to run the tests and getting the error as follows:

```
> cypress run --browser chrome
DevTools listening on ws://127.0.0.1:43545/devtools/browser/a741e86e-5f9e-4052-95f6-73416398ba73
Couldn't find tsconfig.json. tsconfig-paths will be skipped
====================================================================================================
  (Run Starting)
  ┌────────────────────────────────────────────────────────────────────────────────────────────
  │ Cypress:        13.15.2                                                                        │
  │ Browser:        Chrome for (headless)                                                          │
  │ Node Version:   v20.18.0 (/github-action-runner/_work/_tool/node/20.18.0/x64/bin/node)[0m         │
  │                 9m                                                                             │
  │ Specs:          2 found (get-application-settings.cy.js, login.cy.js)                          │
  │ Searched:       cypress/e2e/*.cy.js                                                            │
  │ Experiments:    experimentalMemoryManagement=true,experimentalModifyObstructiveThirdPartyCode… │
  └────────────────────────────────────────────────────────────────────────────────────────────
Remove output folder /github-action-runner/_work/automated.tests/.automated.tests/cypress/reports/html
─────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  get-application-settings.cy.js                                                  (1 of 2)
Launching browser: chrome
Chrome launch options: {
  preferences: { default: {}, defaultSecure: {}, localState: {} },
  args: [
    '--test-type',
    '--ignore-certificate-errors',
    '--start-maximized',
    '--silent-debugger-extension-api',
    '--no-default-browser-check',
    '--no-first-run',
    '--noerrdialogs',
    '--enable-fixed-layout',
    '--disable-popup-blocking',
    '--disable-password-generation',
    '--disable-single-click-autofill',
    '--disable-prompt-on-repos',
    '--disable-background-timer-throttling',
    '--disable-renderer-backgrounding',
    '--disable-renderer-throttling',
    '--disable-backgrounding-occluded-windows',
    '--disable-restore-session-state',
    '--disable-new-profile-management',
    '--disable-new-avatar-menu',
    '--allow-insecure-localhost',
    '--reduce-security-for-testing',
    '--enable-automation',
    '--disable-print-preview',
    '--disable-component-extensions-with-background-pages',
    '--disable-device-discovery-notifications',
    '--autoplay-policy=no-user-gesture-required',
    '--disable-site-isolation-trials',
    '--metrics-recording-only',
    '--disable-prompt-on-repost',
    '--disable-hang-monitor',
    '--disable-sync',
    '--disable-web-resources',
    '--safebrowsing-disable-download-protection',
    '--disable-client-side-phishing-detection',
    '--disable-component-update',
    "--simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'",
    '--disable-default-apps',
    '--disable-features=Translate,PrivacySandboxSettings4',
    '--use-fake-ui-for-media-stream',
    '--use-fake-device-for-media-stream',
    '--disable-ipc-flooding-protection',
    '--disable-backgrounding-occluded-window',
    '--disable-breakpad',
    '--password-store=basic',
    '--use-mock-keychain',
    '--disable-dev-shm-usage',
    '--enable-precise-memory-info',
    '--disable-gpu',
    '--no-sandbox',
    '--disable-web-security',
    '--allow-running-insecure-content',
    '--headless',
    '--window-size=1280,720',
    '--force-device-scale-factor=1',
    '--remote-debugging-port=46227',
    '--remote-debugging-address=127.0.0.1',
    '--disable-gpu',
  ],
  extensions: [],
  env: {},
  concat: [Function (anonymous)],
  push: [Function (anonymous)],
  unshift: [Function (anonymous)],
  slice: [Function (anonymous)],
  pop: [Function (anonymous)],
  shift: [Function (anonymous)],
  splice: [Function (anonymous)],
  filter: [Function (anonymous)],
  map: [Function (anonymous)],
  forEach: [Function (anonymous)],
  reduce: [Function (anonymous)],
  reverse: [Function (anonymous)],
  includes: [Function (anonymous)],
  [Symbol(Symbol.iterator)]: [Function: bound values]
}
Timed out waiting for the browser to connect. Retrying again...

The browser never connected. Something is wrong. The tests cannot run. Aborting...
The browser never connected. Something is wrong. The tests cannot run. Aborting...
```

**Comment by MikeMcC399** [comment] 2024-11-15 10:45
@MikeMcC399 

Are you able to test using the built-in Electron browser instead of Chrome?

**Comment by MikeMcC399** [comment] 2024-11-15 12:18
@mchittineni 

Your workflow with Chrome is failing because:

1. [browser-actions/setup-chrome@v1](https://github.com/browser-actions/setup-chrome) installs "Chrome for Testing". See [Supported version formats](https://github.com/browser-actions/setup-chrome/blob/master/README.md#supported-version-formats).
2. Cypress does not currently work with "Chrome for Testing". It only works with "Chrome". See https://github.com/cypress-io/cypress/issues/28123 and https://github.com/cypress-io/cypress/issues/28554

You can see this in your logs, where instead of the version it shows `for`

```text
1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: for
  - Executable: chrome
```

Your options would be:

1. Install regular "Chrome" instead of "Chrome for Testing" into your runner. https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-google-chrome.sh is the script which GitHub-hosted runners use to do this.
2. Use a [Cypress Docker image](https://github.com/cypress-io/cypress-docker-images) `cypress/browsers` in your workflow. https://github.com/cypress-io/github-action/blob/master/README.md#docker-image describes how to do this.
3. Use a GitHub-hosted runner instead of a self-hosted runner. GitHub-hosted runners have Chrome pre-installed.

---

Note that when you use

```yml
with:
  command: npm run cy:run:chrome
```

instead of

```yml
with:
  browser: chrome
```

you are bypassing most of the functionality of the action. See [Custom test command](https://github.com/cypress-io/github-action/blob/master/README.md#custom-test-command). Specifying the browser with the `browser` option is the preferred way.

---

Thank you for also trying out Electron. The problem you describe that the workflow times out is unlikely to be caused by the Cypress JavaScript Action. You will need to look at that separately.

**Comment by MikeMcC399** [comment] 2024-11-15 12:58
@mchittineni 

> ```
> with:
>   browser: chrome
> ```
> 
> i just used this in github hosted runner, still cypress took electron browser by default

You can check exactly which parameters were passed in the logs if you open up the first line of the step which calls the action, for example:

```text
Run cypress-io/github-action@v6
  with:
    build: npm run build
    start: npm start
    browser: chrome
    record: false
    publish-summary: true
    component: false
```

If the Electron browser is being run, then the Chrome parameter is not being passed. 

Changing to the different syntax will not solve your issue. I just mentioned this point in passing.

**Comment by MikeMcC399** [comment] 2024-11-15 13:37
@mchittineni 

I am surprised that the puppeteer installation works for you as this also installs "Chrome for Testing".

See https://pptr.dev/browsers-api

If you have found a solution then you can close this issue.

---

Please note that this issue list is primarily for reporting bugs and enhancement requests for the Cypress JavaScript Action.

For future "how-to" type support you can connect to the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

**Closed as completed** 2024-11-15 14:26 UTC
Labels: bug
